// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: tx.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RatingValue is a rater's verdict on a note (mapped to fixed-point {1000,500,0} during scoring).
type RatingValue int32

const (
	RatingValue_RATING_UNSPECIFIED RatingValue = 0
	RatingValue_RATING_HELPFUL     RatingValue = 1
	RatingValue_RATING_SOMEWHAT    RatingValue = 2
	RatingValue_RATING_NOT_HELPFUL RatingValue = 3
)

// Enum value maps for RatingValue.
var (
	RatingValue_name = map[int32]string{
		0: "RATING_UNSPECIFIED",
		1: "RATING_HELPFUL",
		2: "RATING_SOMEWHAT",
		3: "RATING_NOT_HELPFUL",
	}
	RatingValue_value = map[string]int32{
		"RATING_UNSPECIFIED": 0,
		"RATING_HELPFUL":     1,
		"RATING_SOMEWHAT":    2,
		"RATING_NOT_HELPFUL": 3,
	}
)

func (x RatingValue) Enum() *RatingValue {
	p := new(RatingValue)
	*p = x
	return p
}

func (x RatingValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RatingValue) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[0].Descriptor()
}

func (RatingValue) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[0]
}

func (x RatingValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RatingValue.Descriptor instead.
func (RatingValue) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

// NoteStatus is a note's on-chain status, recomputed each block by the bridging scorer.
type NoteStatus int32

const (
	NoteStatus_NOTE_STATUS_UNSPECIFIED NoteStatus = 0
	NoteStatus_NEEDS_MORE_RATINGS      NoteStatus = 1
	NoteStatus_HELPFUL                 NoteStatus = 2
	NoteStatus_NOT_HELPFUL             NoteStatus = 3
)

// Enum value maps for NoteStatus.
var (
	NoteStatus_name = map[int32]string{
		0: "NOTE_STATUS_UNSPECIFIED",
		1: "NEEDS_MORE_RATINGS",
		2: "HELPFUL",
		3: "NOT_HELPFUL",
	}
	NoteStatus_value = map[string]int32{
		"NOTE_STATUS_UNSPECIFIED": 0,
		"NEEDS_MORE_RATINGS":      1,
		"HELPFUL":                 2,
		"NOT_HELPFUL":             3,
	}
)

func (x NoteStatus) Enum() *NoteStatus {
	p := new(NoteStatus)
	*p = x
	return p
}

func (x NoteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_proto_enumTypes[1].Descriptor()
}

func (NoteStatus) Type() protoreflect.EnumType {
	return &file_tx_proto_enumTypes[1]
}

func (x NoteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoteStatus.Descriptor instead.
func (NoteStatus) EnumDescriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

// Transaction represents a request or action submitted to the network like transfer assets or perform other operations
// within the blockchain system - THIS MUST MATCH lib.Transaction EXACTLY for signing
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type: The type of the transaction like 'send' or 'stake'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	// msg: The actual transaction message payload, which is encapsulated in a generic message format
	Msg *anypb.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// signature: The cryptographic signature used to verify the authenticity of the transaction
	Signature *Signature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// created_height: The height when the transaction was created - allows 'safe pruning'
	CreatedHeight uint64 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	// time: The timestamp when the transaction was created - used as temporal entropy to prevent hash collisions in txs
	Time uint64 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	// fee: The fee associated with processing the transaction
	Fee uint64 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	// memo: An optional message or note attached to the transaction
	Memo string `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	// network_id: The identity of the network the transaction is intended for
	NetworkId uint64 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	// chain_id: The identity of the committee the transaction is intended for
	ChainId       uint64 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"` // @gotags: json:"chainID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// MessageSend is a standard transfer transaction, taking tokens from the sender and transferring
// them to the recipient
type MessageSend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_address: is the sender of the funds
	FromAddress []byte `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	// to_address: is the recipient of the funds
	ToAddress []byte `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"` // @gotags: json:"toAddress"
	// amount: is the amount of tokens in micro-denomination (uCNPY)
	Amount        uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// MessageSubmitClaim registers a claim (a post/URL/statement that may need context).
type MessageSubmitClaim struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// submitter: the address registering the claim (the authorized signer)
	Submitter []byte `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// content_hash: hash of the claim text/target (non-empty unless url is set)
	ContentHash []byte `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"contentHash"` // @gotags: json:"contentHash"
	// url: optional URL the claim refers to
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// text: short human-readable claim text
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// nonce: caller-chosen value for deterministic id derivation + replay distinction
	Nonce         uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSubmitClaim) Reset() {
	*x = MessageSubmitClaim{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSubmitClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSubmitClaim) ProtoMessage() {}

func (x *MessageSubmitClaim) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSubmitClaim.ProtoReflect.Descriptor instead.
func (*MessageSubmitClaim) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MessageSubmitClaim) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *MessageSubmitClaim) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *MessageSubmitClaim) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MessageSubmitClaim) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageSubmitClaim) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// MessageSubmitNote attaches a note to an existing claim.
type MessageSubmitNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// author: the address writing the note (the authorized signer)
	Author []byte `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	// claim_id: the claim this note is attached to
	ClaimId []byte `protobuf:"bytes,2,opt,name=claim_id,json=claimId,proto3" json:"claimId"` // @gotags: json:"claimId"
	// body: the note text
	Body string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// content_hash: optional hash of supporting material
	ContentHash []byte `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"contentHash"` // @gotags: json:"contentHash"
	// nonce: caller-chosen value for deterministic id derivation
	Nonce uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// url: optional source URL backing the note (additive; mirrors MessageSubmitClaim.url)
	Url           string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSubmitNote) Reset() {
	*x = MessageSubmitNote{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSubmitNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSubmitNote) ProtoMessage() {}

func (x *MessageSubmitNote) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSubmitNote.ProtoReflect.Descriptor instead.
func (*MessageSubmitNote) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MessageSubmitNote) GetAuthor() []byte {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *MessageSubmitNote) GetClaimId() []byte {
	if x != nil {
		return x.ClaimId
	}
	return nil
}

func (x *MessageSubmitNote) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MessageSubmitNote) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *MessageSubmitNote) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *MessageSubmitNote) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// MessageRateNote rates a note (one rating per note+rater; later ratings overwrite).
type MessageRateNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rater: the address rating the note (the authorized signer)
	Rater []byte `protobuf:"bytes,1,opt,name=rater,proto3" json:"rater,omitempty"`
	// note_id: the note being rated
	NoteId []byte `protobuf:"bytes,2,opt,name=note_id,json=noteId,proto3" json:"noteId"` // @gotags: json:"noteId"
	// value: the rater's verdict
	Value RatingValue `protobuf:"varint,3,opt,name=value,proto3,enum=types.RatingValue" json:"value,omitempty"`
	// nonce: caller-chosen value
	Nonce         uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRateNote) Reset() {
	*x = MessageRateNote{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRateNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRateNote) ProtoMessage() {}

func (x *MessageRateNote) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRateNote.ProtoReflect.Descriptor instead.
func (*MessageRateNote) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessageRateNote) GetRater() []byte {
	if x != nil {
		return x.Rater
	}
	return nil
}

func (x *MessageRateNote) GetNoteId() []byte {
	if x != nil {
		return x.NoteId
	}
	return nil
}

func (x *MessageRateNote) GetValue() RatingValue {
	if x != nil {
		return x.Value
	}
	return RatingValue_RATING_UNSPECIFIED
}

func (x *MessageRateNote) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// Claim is the persisted claim record (key prefix 24).
type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"contentHash"` // @gotags: json:"contentHash"
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Submitter     []byte                 `protobuf:"bytes,5,opt,name=submitter,proto3" json:"submitter,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,6,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *Claim) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Claim) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *Claim) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Claim) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Claim) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *Claim) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

// Note is the persisted note record (key prefix 25).
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClaimId       []byte                 `protobuf:"bytes,2,opt,name=claim_id,json=claimId,proto3" json:"claimId"` // @gotags: json:"claimId"
	Author        []byte                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"contentHash"`        // @gotags: json:"contentHash"
	CreatedHeight uint64                 `protobuf:"varint,6,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	Status        NoteStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=types.NoteStatus" json:"status,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *Note) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Note) GetClaimId() []byte {
	if x != nil {
		return x.ClaimId
	}
	return nil
}

func (x *Note) GetAuthor() []byte {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Note) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Note) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *Note) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Note) GetStatus() NoteStatus {
	if x != nil {
		return x.Status
	}
	return NoteStatus_NOTE_STATUS_UNSPECIFIED
}

func (x *Note) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Rating is a persisted rating record (key prefix 26).
type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        []byte                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"noteId"` // @gotags: json:"noteId"
	Rater         []byte                 `protobuf:"bytes,2,opt,name=rater,proto3" json:"rater,omitempty"`
	Value         RatingValue            `protobuf:"varint,3,opt,name=value,proto3,enum=types.RatingValue" json:"value,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *Rating) GetNoteId() []byte {
	if x != nil {
		return x.NoteId
	}
	return nil
}

func (x *Rating) GetRater() []byte {
	if x != nil {
		return x.Rater
	}
	return nil
}

func (x *Rating) GetValue() RatingValue {
	if x != nil {
		return x.Value
	}
	return RatingValue_RATING_UNSPECIFIED
}

func (x *Rating) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

// Reputation is non-transferable rater/author reputation (key prefix 27), fixed-point x1000.
type Reputation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Account          []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ScoreFp          int64                  `protobuf:"varint,2,opt,name=score_fp,json=scoreFp,proto3" json:"scoreFP"`                              // @gotags: json:"scoreFP"
	LastActiveHeight uint64                 `protobuf:"varint,3,opt,name=last_active_height,json=lastActiveHeight,proto3" json:"lastActiveHeight"` // @gotags: json:"lastActiveHeight"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Reputation) Reset() {
	*x = Reputation{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reputation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reputation) ProtoMessage() {}

func (x *Reputation) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reputation.ProtoReflect.Descriptor instead.
func (*Reputation) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *Reputation) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Reputation) GetScoreFp() int64 {
	if x != nil {
		return x.ScoreFp
	}
	return 0
}

func (x *Reputation) GetLastActiveHeight() uint64 {
	if x != nil {
		return x.LastActiveHeight
	}
	return 0
}

// ClaimCreatedEvent is emitted by DeliverTx when a claim is registered.
type ClaimCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       []byte                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claimId"` // @gotags: json:"claimId"
	Submitter     []byte                 `protobuf:"bytes,2,opt,name=submitter,proto3" json:"submitter,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"contentHash"` // @gotags: json:"contentHash"
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,5,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCreatedEvent) Reset() {
	*x = ClaimCreatedEvent{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCreatedEvent) ProtoMessage() {}

func (x *ClaimCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCreatedEvent.ProtoReflect.Descriptor instead.
func (*ClaimCreatedEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimCreatedEvent) GetClaimId() []byte {
	if x != nil {
		return x.ClaimId
	}
	return nil
}

func (x *ClaimCreatedEvent) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *ClaimCreatedEvent) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *ClaimCreatedEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ClaimCreatedEvent) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *ClaimCreatedEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// NoteCreatedEvent is emitted by DeliverTx when a note is attached to a claim.
type NoteCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        []byte                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"noteId"`    // @gotags: json:"noteId"
	ClaimId       []byte                 `protobuf:"bytes,2,opt,name=claim_id,json=claimId,proto3" json:"claimId"` // @gotags: json:"claimId"
	Author        []byte                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"contentHash"`        // @gotags: json:"contentHash"
	CreatedHeight uint64                 `protobuf:"varint,6,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	Status        NoteStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=types.NoteStatus" json:"status,omitempty"`              // initial status (NEEDS_MORE_RATINGS)
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteCreatedEvent) Reset() {
	*x = NoteCreatedEvent{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteCreatedEvent) ProtoMessage() {}

func (x *NoteCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteCreatedEvent.ProtoReflect.Descriptor instead.
func (*NoteCreatedEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *NoteCreatedEvent) GetNoteId() []byte {
	if x != nil {
		return x.NoteId
	}
	return nil
}

func (x *NoteCreatedEvent) GetClaimId() []byte {
	if x != nil {
		return x.ClaimId
	}
	return nil
}

func (x *NoteCreatedEvent) GetAuthor() []byte {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *NoteCreatedEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NoteCreatedEvent) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *NoteCreatedEvent) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *NoteCreatedEvent) GetStatus() NoteStatus {
	if x != nil {
		return x.Status
	}
	return NoteStatus_NOTE_STATUS_UNSPECIFIED
}

func (x *NoteCreatedEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// NoteRatedEvent is emitted by DeliverTx when a rating lands (new or overwrite).
type NoteRatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        []byte                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"noteId"` // @gotags: json:"noteId"
	Rater         []byte                 `protobuf:"bytes,2,opt,name=rater,proto3" json:"rater,omitempty"`
	Value         RatingValue            `protobuf:"varint,3,opt,name=value,proto3,enum=types.RatingValue" json:"value,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteRatedEvent) Reset() {
	*x = NoteRatedEvent{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteRatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteRatedEvent) ProtoMessage() {}

func (x *NoteRatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteRatedEvent.ProtoReflect.Descriptor instead.
func (*NoteRatedEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *NoteRatedEvent) GetNoteId() []byte {
	if x != nil {
		return x.NoteId
	}
	return nil
}

func (x *NoteRatedEvent) GetRater() []byte {
	if x != nil {
		return x.Rater
	}
	return nil
}

func (x *NoteRatedEvent) GetValue() RatingValue {
	if x != nil {
		return x.Value
	}
	return RatingValue_RATING_UNSPECIFIED
}

func (x *NoteRatedEvent) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

// NoteScoredEvent is emitted by EndBlock every time a note is rescored by the bridging algorithm.
// It carries the full breakdown (cohort means/counts + bridge score) so the status (changed or not)
// and the reason for it are observable over RPC and visualizable in the UI.
type NoteScoredEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NoteId      []byte                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"noteId"`    // @gotags: json:"noteId"
	ClaimId     []byte                 `protobuf:"bytes,2,opt,name=claim_id,json=claimId,proto3" json:"claimId"` // @gotags: json:"claimId"
	Status      NoteStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=types.NoteStatus" json:"status,omitempty"`
	BridgeScore int64                  `protobuf:"varint,4,opt,name=bridge_score,json=bridgeScore,proto3" json:"bridgeScore"` // @gotags: json:"bridgeScore"
	MeanA       int64                  `protobuf:"varint,5,opt,name=mean_a,json=meanA,proto3" json:"meanA"`                   // @gotags: json:"meanA"
	MeanB       int64                  `protobuf:"varint,6,opt,name=mean_b,json=meanB,proto3" json:"meanB"`                   // @gotags: json:"meanB"
	CountA      uint32                 `protobuf:"varint,7,opt,name=count_a,json=countA,proto3" json:"countA"`                // @gotags: json:"countA"
	CountB      uint32                 `protobuf:"varint,8,opt,name=count_b,json=countB,proto3" json:"countB"`                // @gotags: json:"countB"
	Height      uint64                 `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	// matrix-factorization breakdown (the production scorer): a note is HELPFUL when note_intercept
	// clears threshold; note_factor is its position on the latent polarity axis.
	NoteIntercept int64  `protobuf:"varint,10,opt,name=note_intercept,json=noteIntercept,proto3" json:"noteIntercept"` // @gotags: json:"noteIntercept"
	NoteFactor    int64  `protobuf:"varint,11,opt,name=note_factor,json=noteFactor,proto3" json:"noteFactor"`          // @gotags: json:"noteFactor"
	GlobalMu      int64  `protobuf:"varint,12,opt,name=global_mu,json=globalMu,proto3" json:"globalMu"`                // @gotags: json:"globalMu"
	NumRaters     uint32 `protobuf:"varint,13,opt,name=num_raters,json=numRaters,proto3" json:"numRaters"`             // @gotags: json:"numRaters"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteScoredEvent) Reset() {
	*x = NoteScoredEvent{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteScoredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteScoredEvent) ProtoMessage() {}

func (x *NoteScoredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteScoredEvent.ProtoReflect.Descriptor instead.
func (*NoteScoredEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{12}
}

func (x *NoteScoredEvent) GetNoteId() []byte {
	if x != nil {
		return x.NoteId
	}
	return nil
}

func (x *NoteScoredEvent) GetClaimId() []byte {
	if x != nil {
		return x.ClaimId
	}
	return nil
}

func (x *NoteScoredEvent) GetStatus() NoteStatus {
	if x != nil {
		return x.Status
	}
	return NoteStatus_NOTE_STATUS_UNSPECIFIED
}

func (x *NoteScoredEvent) GetBridgeScore() int64 {
	if x != nil {
		return x.BridgeScore
	}
	return 0
}

func (x *NoteScoredEvent) GetMeanA() int64 {
	if x != nil {
		return x.MeanA
	}
	return 0
}

func (x *NoteScoredEvent) GetMeanB() int64 {
	if x != nil {
		return x.MeanB
	}
	return 0
}

func (x *NoteScoredEvent) GetCountA() uint32 {
	if x != nil {
		return x.CountA
	}
	return 0
}

func (x *NoteScoredEvent) GetCountB() uint32 {
	if x != nil {
		return x.CountB
	}
	return 0
}

func (x *NoteScoredEvent) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *NoteScoredEvent) GetNoteIntercept() int64 {
	if x != nil {
		return x.NoteIntercept
	}
	return 0
}

func (x *NoteScoredEvent) GetNoteFactor() int64 {
	if x != nil {
		return x.NoteFactor
	}
	return 0
}

func (x *NoteScoredEvent) GetGlobalMu() int64 {
	if x != nil {
		return x.GlobalMu
	}
	return 0
}

func (x *NoteScoredEvent) GetNumRaters() uint32 {
	if x != nil {
		return x.NumRaters
	}
	return 0
}

// ReputationChangedEvent is emitted by EndBlock when an account's non-transferable reputation moves,
// either from a note resolution (gain/loss) or from inactivity decay. score_fp is the new total.
type ReputationChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ScoreFp       int64                  `protobuf:"varint,2,opt,name=score_fp,json=scoreFp,proto3" json:"scoreFP"` // @gotags: json:"scoreFP"
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // author_helpful | rater_correct | rater_wrong | author_not_helpful | decay
	Height        uint64                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReputationChangedEvent) Reset() {
	*x = ReputationChangedEvent{}
	mi := &file_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputationChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputationChangedEvent) ProtoMessage() {}

func (x *ReputationChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputationChangedEvent.ProtoReflect.Descriptor instead.
func (*ReputationChangedEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{13}
}

func (x *ReputationChangedEvent) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ReputationChangedEvent) GetScoreFp() int64 {
	if x != nil {
		return x.ScoreFp
	}
	return 0
}

func (x *ReputationChangedEvent) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *ReputationChangedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReputationChangedEvent) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// FeeParams is the parameter space that defines various amounts for transaction fees
type FeeParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// send_fee: is the fee amount (in uCNPY) for Message Send
	SendFee       uint64 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"sendFee"` // @gotags: json:"sendFee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{14}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

// A Signature is a digital signature is a cryptographic "fingerprint" created with a private key,
// allowing others to verify the authenticity and integrity of a message using the corresponding public key
type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_key: is a cryptographic code shared openly, used to verify digital signatures
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey"` // @gotags: json:"publicKey"
	// signature: the bytes of the signature output from a private key which may be verified with the message and public
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{15}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\x91\x01\n" +
	"\x12MessageSubmitClaim\x12\x1c\n" +
	"\tsubmitter\x18\x01 \x01(\fR\tsubmitter\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\fR\vcontentHash\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\"\xa5\x01\n" +
	"\x11MessageSubmitNote\x12\x16\n" +
	"\x06author\x18\x01 \x01(\fR\x06author\x12\x19\n" +
	"\bclaim_id\x18\x02 \x01(\fR\aclaimId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\fR\vcontentHash\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"\x80\x01\n" +
	"\x0fMessageRateNote\x12\x14\n" +
	"\x05rater\x18\x01 \x01(\fR\x05rater\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\fR\x06noteId\x12(\n" +
	"\x05value\x18\x03 \x01(\x0e2\x12.types.RatingValueR\x05value\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\"\xa5\x01\n" +
	"\x05Claim\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\fR\vcontentHash\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1c\n" +
	"\tsubmitter\x18\x05 \x01(\fR\tsubmitter\x12%\n" +
	"\x0ecreated_height\x18\x06 \x01(\x04R\rcreatedHeight\"\xe4\x01\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x19\n" +
	"\bclaim_id\x18\x02 \x01(\fR\aclaimId\x12\x16\n" +
	"\x06author\x18\x03 \x01(\fR\x06author\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\fR\vcontentHash\x12%\n" +
	"\x0ecreated_height\x18\x06 \x01(\x04R\rcreatedHeight\x12)\n" +
	"\x06status\x18\a \x01(\x0e2\x11.types.NoteStatusR\x06status\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\x88\x01\n" +
	"\x06Rating\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\fR\x06noteId\x12\x14\n" +
	"\x05rater\x18\x02 \x01(\fR\x05rater\x12(\n" +
	"\x05value\x18\x03 \x01(\x0e2\x12.types.RatingValueR\x05value\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\"o\n" +
	"\n" +
	"Reputation\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\fR\aaccount\x12\x19\n" +
	"\bscore_fp\x18\x02 \x01(\x03R\ascoreFp\x12,\n" +
	"\x12last_active_height\x18\x03 \x01(\x04R\x10lastActiveHeight\"\xbc\x01\n" +
	"\x11ClaimCreatedEvent\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\fR\aclaimId\x12\x1c\n" +
	"\tsubmitter\x18\x02 \x01(\fR\tsubmitter\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\fR\vcontentHash\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12%\n" +
	"\x0ecreated_height\x18\x05 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\"\xf9\x01\n" +
	"\x10NoteCreatedEvent\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\fR\x06noteId\x12\x19\n" +
	"\bclaim_id\x18\x02 \x01(\fR\aclaimId\x12\x16\n" +
	"\x06author\x18\x03 \x01(\fR\x06author\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\fR\vcontentHash\x12%\n" +
	"\x0ecreated_height\x18\x06 \x01(\x04R\rcreatedHeight\x12)\n" +
	"\x06status\x18\a \x01(\x0e2\x11.types.NoteStatusR\x06status\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\x90\x01\n" +
	"\x0eNoteRatedEvent\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\fR\x06noteId\x12\x14\n" +
	"\x05rater\x18\x02 \x01(\fR\x05rater\x12(\n" +
	"\x05value\x18\x03 \x01(\x0e2\x12.types.RatingValueR\x05value\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\"\x8f\x03\n" +
	"\x0fNoteScoredEvent\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\fR\x06noteId\x12\x19\n" +
	"\bclaim_id\x18\x02 \x01(\fR\aclaimId\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.types.NoteStatusR\x06status\x12!\n" +
	"\fbridge_score\x18\x04 \x01(\x03R\vbridgeScore\x12\x15\n" +
	"\x06mean_a\x18\x05 \x01(\x03R\x05meanA\x12\x15\n" +
	"\x06mean_b\x18\x06 \x01(\x03R\x05meanB\x12\x17\n" +
	"\acount_a\x18\a \x01(\rR\x06countA\x12\x17\n" +
	"\acount_b\x18\b \x01(\rR\x06countB\x12\x16\n" +
	"\x06height\x18\t \x01(\x04R\x06height\x12%\n" +
	"\x0enote_intercept\x18\n" +
	" \x01(\x03R\rnoteIntercept\x12\x1f\n" +
	"\vnote_factor\x18\v \x01(\x03R\n" +
	"noteFactor\x12\x1b\n" +
	"\tglobal_mu\x18\f \x01(\x03R\bglobalMu\x12\x1d\n" +
	"\n" +
	"num_raters\x18\r \x01(\rR\tnumRaters\"\x93\x01\n" +
	"\x16ReputationChangedEvent\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\fR\aaccount\x12\x19\n" +
	"\bscore_fp\x18\x02 \x01(\x03R\ascoreFp\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x04R\x06height\"&\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature*f\n" +
	"\vRatingValue\x12\x16\n" +
	"\x12RATING_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRATING_HELPFUL\x10\x01\x12\x13\n" +
	"\x0fRATING_SOMEWHAT\x10\x02\x12\x16\n" +
	"\x12RATING_NOT_HELPFUL\x10\x03*_\n" +
	"\n" +
	"NoteStatus\x12\x1b\n" +
	"\x17NOTE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NEEDS_MORE_RATINGS\x10\x01\x12\v\n" +
	"\aHELPFUL\x10\x02\x12\x0f\n" +
	"\vNOT_HELPFUL\x10\x03B.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_tx_proto_goTypes = []any{
	(RatingValue)(0),               // 0: types.RatingValue
	(NoteStatus)(0),                // 1: types.NoteStatus
	(*Transaction)(nil),            // 2: types.Transaction
	(*MessageSend)(nil),            // 3: types.MessageSend
	(*MessageSubmitClaim)(nil),     // 4: types.MessageSubmitClaim
	(*MessageSubmitNote)(nil),      // 5: types.MessageSubmitNote
	(*MessageRateNote)(nil),        // 6: types.MessageRateNote
	(*Claim)(nil),                  // 7: types.Claim
	(*Note)(nil),                   // 8: types.Note
	(*Rating)(nil),                 // 9: types.Rating
	(*Reputation)(nil),             // 10: types.Reputation
	(*ClaimCreatedEvent)(nil),      // 11: types.ClaimCreatedEvent
	(*NoteCreatedEvent)(nil),       // 12: types.NoteCreatedEvent
	(*NoteRatedEvent)(nil),         // 13: types.NoteRatedEvent
	(*NoteScoredEvent)(nil),        // 14: types.NoteScoredEvent
	(*ReputationChangedEvent)(nil), // 15: types.ReputationChangedEvent
	(*FeeParams)(nil),              // 16: types.FeeParams
	(*Signature)(nil),              // 17: types.Signature
	(*anypb.Any)(nil),              // 18: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	18, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	17, // 1: types.Transaction.signature:type_name -> types.Signature
	0,  // 2: types.MessageRateNote.value:type_name -> types.RatingValue
	1,  // 3: types.Note.status:type_name -> types.NoteStatus
	0,  // 4: types.Rating.value:type_name -> types.RatingValue
	1,  // 5: types.NoteCreatedEvent.status:type_name -> types.NoteStatus
	0,  // 6: types.NoteRatedEvent.value:type_name -> types.RatingValue
	1,  // 7: types.NoteScoredEvent.status:type_name -> types.NoteStatus
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		EnumInfos:         file_tx_proto_enumTypes,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
